"""Initial Feedback Intelligence schema

Revision ID: c6841cc324c1
Revises: 
Create Date: 2026-09-07 12:52:05.544545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'c6841cc324c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('raw_file_path', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('validation_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_dataset_id'), 'analysis_runs', ['dataset_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('segment', sa.String(length=255), nullable=True),
    sa.Column('feedback_ts', sa.DateTime(), nullable=True),
    sa.Column('duplicate_cluster_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_category'), 'feedback', ['category'], unique=False)
    op.create_index('ix_feedback_dataset_category', 'feedback', ['dataset_id', 'category'], unique=False)
    op.create_index(op.f('ix_feedback_dataset_id'), 'feedback', ['dataset_id'], unique=False)
    op.create_index('ix_feedback_dataset_sentiment', 'feedback', ['dataset_id', 'sentiment'], unique=False)
    op.create_index('ix_feedback_dataset_ts', 'feedback', ['dataset_id', 'feedback_ts'], unique=False)
    op.create_index(op.f('ix_feedback_duplicate_cluster_id'), 'feedback', ['duplicate_cluster_id'], unique=False)
    op.create_index(op.f('ix_feedback_feedback_ts'), 'feedback', ['feedback_ts'], unique=False)
    op.create_index(op.f('ix_feedback_sentiment'), 'feedback', ['sentiment'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('parent_topic_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('centroid', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('coherence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_dataset_id'), 'topics', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_topics_parent_topic_id'), 'topics', ['parent_topic_id'], unique=False)
    op.create_table('aspect_sentiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('aspect_text', sa.String(length=255), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aspect_sentiments_feedback_id'), 'aspect_sentiments', ['feedback_id'], unique=False)
    op.create_table('feedback_topics',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('distance_to_centroid', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id', 'topic_id')
    )
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('priority_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trend', sa.String(length=50), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('unique_issue_count', sa.Integer(), nullable=False),
    sa.Column('affected_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('likely_drivers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_dataset_id'), 'insights', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_insights_priority_score'), 'insights', ['priority_score'], unique=False)
    op.create_index(op.f('ix_insights_topic_id'), 'insights', ['topic_id'], unique=False)
    op.create_table('insight_evidence',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('insight_id', 'feedback_id')
    )
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affected_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('linked_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_dataset_id'), 'issues', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_issues_insight_id'), 'issues', ['insight_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=True),
    sa.Column('insight_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('suggested_owner', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('outcome_before', sa.Float(), nullable=True),
    sa.Column('outcome_after', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_insight_id'), 'actions', ['insight_id'], unique=False)
    op.create_index(op.f('ix_actions_issue_id'), 'actions', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actions_issue_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_insight_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_issues_insight_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_dataset_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_table('insight_evidence')
    op.drop_index(op.f('ix_insights_topic_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_priority_score'), table_name='insights')
    op.drop_index(op.f('ix_insights_dataset_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_table('feedback_topics')
    op.drop_index(op.f('ix_aspect_sentiments_feedback_id'), table_name='aspect_sentiments')
    op.drop_table('aspect_sentiments')
    op.drop_index(op.f('ix_topics_parent_topic_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_dataset_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_feedback_sentiment'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_feedback_ts'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_duplicate_cluster_id'), table_name='feedback')
    op.drop_index('ix_feedback_dataset_ts', table_name='feedback')
    op.drop_index('ix_feedback_dataset_sentiment', table_name='feedback')
    op.drop_index(op.f('ix_feedback_dataset_id'), table_name='feedback')
    op.drop_index('ix_feedback_dataset_category', table_name='feedback')
    op.drop_index(op.f('ix_feedback_category'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_analysis_runs_dataset_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_table('model_versions')
    op.drop_table('datasets')
    # ### end Alembic commands ###
